"""Pydantic configuration schemas — SPEC sections 5 and 6.

Imported as ``nocturne.schemas``; the files live under ``config/schemas/`` as
SPEC section 6 requires. See docs/decisions/0003-config-schema-location.md.
"""

from __future__ import annotations

from .agent import (
    ACTION_TOOLS,
    AUTONOMY_LEVELS,
    EVENT_CODES,
    MANDATORY_EVENT_CODES,
    READ_ONLY_TOOLS,
    AgentConfig,
    AutonomyLevel,
)
from .common import ARCSEC_PER_ARCMIN, ARCSEC_PER_RADIAN, StrictModel
from .equipment import (
    CoolingConfig,
    DitherConfig,
    EquipmentConfig,
    FilterSlot,
    FilterType,
    FilterWheel,
    Focuser,
    GainProfile,
    GuideCamera,
    GuideThresholds,
    Guiding,
    GuidingMode,
    ImagingCamera,
    Mount,
    MountConnection,
    OpticalTrain,
    RefocusTriggers,
    Site,
    TemperatureCompensation,
)
from .loader import (
    AGENT_FILENAME,
    EQUIPMENT_FILENAME,
    SAFETY_FILENAME,
    ConfigError,
    NocturneConfig,
    load_agent_config,
    load_config_bundle,
    load_equipment_config,
    load_model,
    load_safety_config,
)
from .safety import (
    AbortAction,
    AbortConditions,
    AgentBudget,
    CoolingLimits,
    DegradationPolicy,
    FlipStrategy,
    Limits,
    MeridianLimits,
    NotifySeverity,
    OnAbort,
    SafetyConfig,
)

__all__ = [
    "ACTION_TOOLS",
    "AGENT_FILENAME",
    "ARCSEC_PER_ARCMIN",
    "ARCSEC_PER_RADIAN",
    "AUTONOMY_LEVELS",
    "EQUIPMENT_FILENAME",
    "EVENT_CODES",
    "MANDATORY_EVENT_CODES",
    "READ_ONLY_TOOLS",
    "SAFETY_FILENAME",
    "AbortAction",
    "AbortConditions",
    "AgentBudget",
    "AgentConfig",
    "AutonomyLevel",
    "ConfigError",
    "CoolingConfig",
    "CoolingLimits",
    "DegradationPolicy",
    "DitherConfig",
    "EquipmentConfig",
    "FilterSlot",
    "FilterType",
    "FilterWheel",
    "FlipStrategy",
    "Focuser",
    "GainProfile",
    "GuideCamera",
    "GuideThresholds",
    "Guiding",
    "GuidingMode",
    "ImagingCamera",
    "Limits",
    "MeridianLimits",
    "Mount",
    "MountConnection",
    "NocturneConfig",
    "NotifySeverity",
    "OnAbort",
    "OpticalTrain",
    "RefocusTriggers",
    "SafetyConfig",
    "Site",
    "StrictModel",
    "TemperatureCompensation",
    "load_agent_config",
    "load_config_bundle",
    "load_equipment_config",
    "load_model",
    "load_safety_config",
]
